# Generated by Django 4.2.3 on 2023-07-08 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('total_passengers', models.IntegerField()),
                ('passengers', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('trainNo', models.IntegerField(default=1)),
                ('compNo', models.IntegerField(default=1)),
                ('facility', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trains', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='train.train')),
                ('users', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='users',
            field=models.ManyToManyField(through='train.TrainReservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
